image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy

before_script:
  - docker info

deploy:
  stage: deploy
  script:
    - docker compose down
    - docker compose pull || true  
    - export JWT_SECRET_KEY="$JWT_SECRET_KEY"
    - docker compose up -d --build --remove-orphans
    - docker system prune -f 
  only:
    - main