image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - deploy

before_script:
  - docker info

deploy:
  stage: deploy
  script:
    - echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" > .env
    - echo "JWT_ISSUER=$JWT_ISSUER" >> .env
    - echo "JWT_AUDIENCE=$JWT_AUDIENCE" >> .env
    - echo "DefaultConnection=$DefaultConnection" >> .env

    - docker compose down
    - docker compose pull || true
    - docker compose up -d --build --remove-orphans
    - docker system prune -f
  only:
    - main