version: '3.8'

services:
  adminpanel-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adminpanel-back
    ports:
      - "8082:8080"
    restart: unless-stopped
    